---
- hosts: webserver
  gather_facts: false

  vars_files:
    - ./vars/vars.yml
    - "./vars/vault/{{ app_env }}.yml"

  environment:
    APP_ENV: "{{ app_env }}"

  pre_tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
      tags:
        - install

  roles:
    - php-cli
    - app_init
    - rabbitmq
    - { role: nginx, nginx_site_name: "{{ site_name }}", nginx_root_dir: "{{ project_dir }}/public", nginx_user: "{{ app_user }}" }
    - php-fpm
    - mysql
    - { role: supervisor, supervisor_user: "{{ app_user }}", supervisor_app_directory: "{{ project_dir }}", supervisor_app_public_directory: "{{ project_dir }}/public"}
    - redis

  tasks:
    - name: Deploy git code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        force: yes
      tags:
        - deploy

    - include: ./includes/symfony-bootstrap.yml
