---
- hosts: all
  gather_facts: false

  vars_files:
    - ./vars/vars.yml

  vars_prompt:
    - name: app_env
      prompt: "Enter the environment for your Symfony app (prod|staging)"
      default: prod
      private: no

  environment:
      APP_ENV: "{{ app_env }}"

  pre_tasks:
    - name: Convert entered Symfony environment to lowercase
      set_fact:
        symfony_env: "{{ app_env|lower }}"
      tags:
        - always

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
      tags:
        - install


  roles:
    - php-cli
    - app_init
    - { role: apache2, apache2_site_name: "{{ site_name }}", apache2_site_directory: "{{ project_dir }}/public", apache2_app_user: "{{ app_user }}"}
    - php-apache2
    - mysql

  tasks:
    - name: Deploy git code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        force: yes
      tags:
        - deploy

    - include: ./includes/symfony-bootstrap.yml
