---
- name: Add nginx repository
  become: yes
  apt_repository:
    repo: ppa:ondrej/nginx-mainline
    state: present
    update_cache: yes
  tags:
    - install


- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: present
  tags:
    - install
    - rabbit

- name: Copy nginx site.conf
  become: yes
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/default
  tags:
    - install

- name: Create site dir
  become: yes
  file:
    path: "{{ nginx_root_dir }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0755'
  tags:
    - install
