---
- name: Install mysql packages
  become: yes
  apt:
    name: "{{ mysql_packages }}"
    state: present
  tags:
    - install

- name: Ensure mysql is started
  become: yes
  service:
    name: mysql
    state: started
    enabled: yes
  tags:
    - install

- name: Change mysql root password
  become: yes
  shell: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  tags:
    - install

- name: Create mysql db
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ db_name }}"
    state: present
  tags:
    - install

- name: Check mysql query
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query: "SELECT NOW()"
  register: query_result
  tags:
    - install

- name: Show mysql query result
  debug:
    var: query_result
  tags:
    - install
