---
- name: Install php-fpm packages
  become: yes
  apt:
    name: php7.4-fpm
    state: present
  tags:
    - install

- name: Copy php-fpm.conf
  become: yes
  notify:
    - Reload php-fpm
  changed_when: yes
  template:
    src: server.conf.j2
    dest: "/etc/php/7.4/fpm/pool.d/{{ php_fpm_user }}.conf"
  tags:
    - install
